<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_BOT_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        'api_url'=>env('BASE_BOT_URL'),
        'timeout' => 86400
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
    // ["message", "edited_message", "channel_post","chosen_inline_result","shipping_query", "pre_checkout_query","poll","poll_answer","edited_channel_post", "callback_query","chat_member","inline_query","my_chat_member","chat_member"]
];
